#!/bin/bash

if [ $# -lt 1 ]; then 
	echo "Usage: $0 <tex files to preview>"
	exit -1;
fi

for arg in "$@"; do
	FNBASE="$(basename $arg)"
	FN="${FNBASE%%.*}"
	(echo "set term lua tikz color solid fontscale 1.3; set out \"$FN.tikz\""; cat $FNBASE) | gnuplot;
	(echo "set term lua tikz color createstyle standalone solid preamble \"\\\\usepackage{siunitx}\\n\\\\usepackage{palatino}\"; set out \"$FN.tex\""; cat $FNBASE) | gnuplot;

	latexmk -silent -pdf -gg -pv $FN.tex
	latexmk -silent -c $FN.tex

	rm $FN.tex
#	rm gnuplot-lua-tikz.sty
	rm gnuplot-lua-tikz.tex
#	rm gnuplot-lua-tikz-common.tex
	rm t-gnuplot-lua-tikz.tex
done
